language: node_js
node_js:
  - "4.2.1"
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
before_script:
  - ./node_modules/ethereumjs-testrpc/bin/testrpc
script: node ./node_modules/truffle/cli.js test